version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.3.7
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command:
            gem update --system
            gem install bundler
            bundle install
      - run:
          name: Build
          command: bundle exec jekyll build --verbose
      - run:
          name: Test
          command: bundle exec htmlproofer ./_site --check-html --disable-external
