version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.3.7
        environment:
          BUNDLER_VERSION: 2.0.1
    steps:
      - checkout
      - run:
          name: Dependencies
          command: bundle install
      - run:
          name: Build
          command: bundle exec jekyll build --verbose
      - run:
          name: Test
          command: bundle exec htmlproofer ./_site --check-html --disable-external
