version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.5.0
    steps:
      - checkout
      - run:
          name: Dependencies
          command: gem install bundler
          command: bundle install
      - run:
          name: Build
          command: bundle exec jekyll build --verbose
      - run:
          name: Test
          command: bundle exec htmlproofer ./_site --check-html --disable-external
